#!/bin/bash

#
# Template driver script to generate A-Prime coupled diagnostics on ACME machines
#  (Supported machines/HPC centers as of June 2017 are: Edison, OLCF, aims4/acme1 and LANL)
#
# Basic usage:
#       1. copy this template to something like run_aprime_$user.bash
#       2. open run_aprime_$user.bash and set user defined, case-specific variables
#       3. execute: ./run_aprime_$user.bash 

# Meaning of acronyms/words used in variable names below:
#	test:		 Test case
#	ref:		 Reference case or 'obs'
#	ts: 		 Time series; e.g. test_begin_yr_ts, here ts refers to time series
#       climateIndex_ts: Time series for climate indexes such as Nino3.4.
#                        NB: if begin_yr_climateIndex_ts=1 and end_yr_climateIndex_ts=9999, the
#                        climate index time series is computed over the full available data set
#	climo: 		 Climatology
#	begin_yr: 	 Model year to start analysis 
#	end_yr:		 Model year to end analysis
#       condense:        Create a new file for each variable with time series data for that variable.
#                        This is used to create climatology (if not pre-computed) and in generating time series plots
#	archive_dir:	 Location of model generated output directory
#	scratch_dir:	 Location of directory where the user wants to store files generated by the diagnostics.
#			 This includes climos, remapped climos, condensed files and data files used for plotting. 
#	short_term_archive:   Adds /atm/hist after the casename. If the data sits in a different structure, add it after
#	                      the casename in test_casename 

# USER DEFINED CASE SPECIFIC VARIABLES TO SPECIFY (REQUIRED)

# Main directory where all analysis output is stored
# (e.g., plots will go in a specific subdirectory of $output_base_dir,
# as will log files, generated climatologies, etc)
export output_base_dir=/dir/to/analysis/output

# MACHINE SPECIFIC VARIABLES (no need to modify these in most cases)
if [ ${HOSTNAME:0:6} == "edison" ]; then
  export machname="nersc"
elif [ ${HOSTNAME:0:4} == "rhea" ] || [ ${HOSTNAME:0:5} == "titan" ]; then
  export machname="olcf"
elif [ ${HOSTNAME:0:5} == "aims4" ]; then
  export machname="aims4"
elif [ ${HOSTNAME:0:5} == "acme1" ]; then
  export machname="acme1"
elif [ ${HOSTNAME:0:4} == "wolf" ]; then
  export machname="lanl"
else
  echo "Unsupported host $HOSTNAME. Exiting."
  exit 1
fi
# Define project and www directories
if [ $machname == "nersc" ]; then
  # Project directory
  projdir=/global/project/projectdirs/acme
  # Location of website directory to host the webpage
  export www_dir=/global/project/projectdirs/acme/www/$USER
elif [ $machname == "olcf" ]; then
  projdir=$PROJWORK/cli115
  export www_dir=/ccs/proj/cli115/www/$USER
elif [ $machname == "aims4" ] || [ $machname == "acme1" ]; then
  projdir=/space2
  export www_dir=/var/www/acme/acme-diags/$USER
elif [ $machname == "lanl" ]; then
  projdir=/usr/projects/climate/SHARED_CLIMATE
  export www_dir=$output_base_dir/www
fi

# Variables relevant for main test case
export test_casename=casename
# NB: $test_casename will be appended to $test_archive_dir
export test_archive_dir=/dir/to/data
export test_short_term_archive=0
#
# Atmosphere grid resolution name (e.g. ne30, ne60, ne120) 
export test_atm_res=ne30
# MPAS mesh name (e.g. oEC60to30v1, oEC60to30v3, oRRS18to6v1)
#   NB: test_atm_res and test_mpas_mesh_name may change with a different choice of test_casename!
export test_mpas_mesh_name=oEC60to30v3
#
export test_begin_yr_climo=31
export test_end_yr_climo=40
export test_begin_yr_ts=1
export test_end_yr_ts=30
export test_begin_yr_climateIndex_ts=1
export test_end_yr_climateIndex_ts=9999

# Atmosphere switches (True(1)/False(0)) to condense variables, compute climos, remap climos and condensed time series file
# If no pre-processing is done (climatology, remapping), all the switches below should be 1
# If a switch is 0, then the user should ensure that the needed files are in the scratch directory (defined below)
# If a switch is 0 for climo, then the user should ensure that the files in the scratch directory correspond to the intended begin and end years set above.
export test_compute_climo=1
export test_remap_climo=1
export test_condense_field_climo=1	# ignored if test_compute_climo = 0
					# if test_condense_field_climo = 1 and test_compute_climo = 0
					# the script will look for a condensed file 
export test_condense_field_ts=1
export test_remap_ts=1

# Reference case variables (similar to test_case variables)
export ref_case=obs
if [ $machname == "nersc" ]; then
  export ref_archive_dir=$projdir/obs_for_diagnostics
elif [ $machname == "olcf" ]; then
  export ref_archive_dir=/lustre/atlas1/cli900/world-shared/obs_for_diagnostics
elif [ $machname == "aims4" ] || [ $machname == "acme1" ]; then
  export ref_archive_dir=/space2/ACME_obs_data/acme-repo/acme/obs_for_diagnostics
elif [ $machname == "lanl" ]; then
  export ref_archive_dir=$projdir/obs_for_diagnostics
fi
#export ref_case=casename
#export ref_archive_dir=dir/to/refcase_data	# $ref_case will be appended to this
export ref_short_term_archive=0

# ACMEv0 ref_case info for ocn/ice diags
#  IMPORTANT: the ACMEv0 model data MUST have been pre-processed.
#  If this pre-processed data is not available, set ref_case_v0 to None.
export ref_case_v0=B1850C5_ne30_v0.4
if [ $machname == "nersc" ]; then
  export ref_archive_v0_ocndir=$projdir/ACMEv0_lowres/${ref_case_v0}/ocn/postprocessing
  export ref_archive_v0_seaicedir=$projdir/ACMEv0_lowres/${ref_case_v0}/ice/postprocessing
elif [ $machname == "olcf" ]; then
  export ref_archive_v0_ocndir=$projdir/milena/ACMEv0_lowres/${ref_case_v0}/ocn/postprocessing
  export ref_archive_v0_seaicedir=$projdir/milena/ACMEv0_lowres/${ref_case_v0}/ice/postprocessing
elif [ $machname == "aims4" ] || [ $machname == "acme1" ]; then
  export ref_archive_v0_ocndir=/space2/diagnostics/ACMEv0_lowres/${ref_case_v0}/ocn/postprocessing
  export ref_archive_v0_seaicedir=/space2/diagnostics/ACMEv0_lowres/${ref_case_v0}/ice/postprocessing
elif [ $machname == "lanl" ]; then
  export ref_archive_v0_ocndir=$projdir/ACMEv0_lowres/${ref_case_v0}/ocn/postprocessing
  export ref_archive_v0_seaicedir=$projdir/ACMEv0_lowres/${ref_case_v0}/ice/postprocessing
fi

# The following are ignored if ref_case=obs
export ref_atm_res=ne30
export ref_mpas_mesh_name=oEC60to30v3
#
export ref_begin_yr_climo=95
export ref_end_yr_climo=100
export ref_begin_yr_ts=95
export ref_end_yr_ts=100
export ref_begin_yr_climateIndex_ts=1
export ref_end_yr_climateIndex_ts=9999
#
export ref_compute_climo=1
export ref_remap_climo=1
export ref_condense_field_climo=1
export ref_condense_field_ts=1
export ref_remap_ts=1

# Select sets of diagnostics to generate (False = 0, True = 1)
export generate_atm_diags=1
export generate_ocnice_diags=1

# The following ocn/ice diagnostic switches are ignored if generate_ocnice_diags is set to 0
export generate_ohc_trends=1
export generate_sst_trends=1
export generate_sst_climo=1
export generate_sss_climo=1
export generate_mld_climo=1
export generate_moc=1
export generate_mht=1
export generate_seaice_trends=1
export generate_seaice_climo=1
export generate_nino34=1

# Generate standalone html file to view plots on a browser, if required
export generate_html=1

# Set options to run a-prime in parallel
#   If run_batch_script=false, aprime_atm_diags.bash and aprime_ocnice_diags.bash are called directly.
#   If run_batch_script=true, aprime_atm_diags.bash and aprime_ocnice_diags.bash are called within
#     a machine-specific batch script (one script for atm and one for ocn/ice diags). In this case,
#     atmosphere diagnostics are run in background mode onto a single compute node. Ocean/ice
#     diagnostics, on the other hand, grab a number of compute nodes set by 'mpas_analysis_tasks':
#     each ocn/ice task is run on a different node. If all ocn/ice diagnostics are run (by activating
#     all the 'generate' options above), the total number of tasks is equal to 10, hence the default
#     here is 10. The user can decide to reduce mpas_analysis_tasks accordingly, if asking to compute
#     a reduced set of ocn/ice diagnostics. Finally, the user can set the walltime (default is 1hr
#     for atm and 1hr for ocn/ice diags, which is fine to compute ~20 year climatology at low-resolution).
export run_batch_script=false
export mpas_analysis_tasks=10
export batch_walltime="01:00:00" # HH:MM:SS

###############################################################################################

# OTHER VARIABLES (NOT REQUIRED TO BE CHANGED BY THE USER - DEFAULTS SHOULD WORK, USER PREFERENCE BASED CHANGES)

if [ $ref_case == "obs" ]; then
  export plots_dir_name=coupled_diagnostics_${test_casename}_years${test_begin_yr_climo}-${test_end_yr_climo}_vs_${ref_case}
else
  export plots_dir_name=coupled_diagnostics_${test_casename}_years${test_begin_yr_climo}-${test_end_yr_climo}_vs_${ref_case}_years${ref_begin_yr_climo}-${ref_end_yr_climo}
fi

# User can set a custom name for the $plot_dir_name here, if the default (above) is not ideal 
#export plots_dir_name=XXYYY

# Set paths to scratch, logs and plots directories
export test_scratch_dir=$output_base_dir/$plots_dir_name.scratch
export ref_scratch_dir=$output_base_dir/$plots_dir_name.scratch
export log_dir=$output_base_dir/$plots_dir_name.logs
export plots_dir=$output_base_dir/$plots_dir_name

# Set atm specific paths to mapping and data files locations
export remap_files_dir=$projdir/mapping/maps
export GPCP_regrid_wgt_file=$projdir/mapping/maps/$test_atm_res-to-GPCP.conservative.wgts.nc
export CERES_EBAF_regrid_wgt_file=$projdir/mapping/maps/$test_atm_res-to-CERES-EBAF.conservative.wgts.nc
export ERS_regrid_wgt_file=$projdir/mapping/maps/$test_atm_res-to-ERS.conservative.wgts.nc

# Set ocn/ice specific paths to mapping and region masking file locations
#     remap from MPAS mesh to regular 0.5degx0.5deg grid
#     NB: if this file does not exist, it will be generated by the analysis
export mpas_remapfile=$projdir/mpas_analysis/mapping/map_${test_mpas_mesh_name}_to_0.5x0.5degree_bilinear.nc
#     MPAS-O region mask files containing masking information for the Atlantic basin
#     NB: this file, instead, *needs* to be present 
if [ $machname == "lanl" ] || [ $machname == "aims4" ] || [ $machname == "acme1" ]; then
  export mpaso_regions_file=$projdir/mpas_analysis/region_masks/${test_mpas_mesh_name}_Atlantic_region_and_southern_transect.nc
else
  export mpaso_regions_file=$projdir/mapping/grids/${test_mpas_mesh_name}_SingleRegionAtlanticWTransportTransects_masks.nc
fi

# Set ocn/ice specific paths to data file names and locations
if [ $machname == "nersc" ]; then
  export obs_ocndir=$projdir/observations/Ocean
  export obs_seaicedir=$projdir/observations/SeaIce
elif [ $machname == "olcf" ]; then
  export obs_ocndir=$projdir/observations
  export obs_seaicedir=$projdir/observations/SeaIce
elif [ $machname == "aims4" ] || [ $machname == "acme1" ]; then
  export obs_ocndir=$projdir/diagnostics/observations/Ocean
  export obs_seaicedir=$projdir/diagnostics/observations/SeaIce
elif [ $machname == "lanl" ]; then
  export obs_ocndir=$projdir/observations
  export obs_seaicedir=$projdir/observations/SeaIce
fi
export obs_sstdir=$obs_ocndir/SST
export obs_sssdir=$obs_ocndir/SSS
export obs_mlddir=$obs_ocndir/MLD
export obs_ninodir=$obs_ocndir/Nino
export obs_mhtdir=$obs_ocndir/MHT
export obs_iceareaNH=$obs_seaicedir/IceArea_timeseries/iceAreaNH_climo.nc
export obs_iceareaSH=$obs_seaicedir/IceArea_timeseries/iceAreaSH_climo.nc
export obs_icevolNH=$obs_seaicedir/PIOMAS/PIOMASvolume_monthly_climo.nc
export obs_icevolSH=none

##############################################################################

######### USER SHOULD NOT NEED TO CHANGE ANYTHING HERE ONWARDS ###############

export coupled_diags_home=$PWD
# unique ID to be used to name unique MPAS-Analysis confg files
# and batch scripts
export uniqueID=`date +%Y-%m-%d_%H%M%S`

# Check on www_dir, permissions included
chmod a+rx $www_dir
# Create www_dir if it does not exist, purge it if it does
if [ ! -d $www_dir/$plots_dir_name ]; then
  mkdir $www_dir/$plots_dir_name
else
  rm -f $www_dir/$plots_dir_name/*
fi
chmod a+r $www_dir/$plots_dir_name

# LOAD THE MACHINE-SPECIFIC ANACONDA-2.7 ENVIRONMENT
source $MODULESHOME/init/bash  
if [ $machname == "nersc" ]; then
  module unload python
  module unload python_base
  module use $projdir/software/modulefiles/all
  module load python/anaconda-2.7-acme
elif [ $machname == "olcf" ]; then
  module unload python
  module use /ccs/proj/cli115/pwolfram/modulefiles/all
  module load python/anaconda-2.7-climate
elif [ $machname == "aims4" ] || [ $machname == "acme1" ]; then
  echo
  echo "*** Need to set/run the following:"
  echo "***  export PATH=/usr/local/anaconda2/bin:$PATH"
  echo "***  source activate ACME-UNIFIED   # (on aims4)"
  echo "***  source activate ACME_UNIFIED   # (on acme1)"
  echo
elif [ $machname == "llnl" ]; then
  module unload python
  module use $projdir/modulefiles/all
  module load python/anaconda-2.7-climate
fi

# PUT THE PROVIDED CASE INFORMATION IN CSH ARRAYS TO FACILITATE READING BY OTHER SCRIPTS
./bash_scripts/setup.bash

# RUN DIAGNOSTICS
if [ $generate_atm_diags -eq 1 ]; then
  # Check whether requested files for computing climatologies are available
  rpointer_file=${test_archive_dir}/${test_casename}/run/rpointer.atm
  year_max=`grep -m 1 -Eo '\<[0-9]{4}\>' ${rpointer_file} | awk '{print $1-1}'`

  if [ $test_end_yr_climo -le $year_max ]; then

    if ! $run_batch_script; then

      ./bash_scripts/aprime_atm_diags.bash

      atm_status=$?

      if [ $atm_status -eq 0 ]; then
        # Update www/plots directory with newly generated plots
        cp -u $plots_dir/* $www_dir/$plots_dir_name

        echo
        echo "Updated atm plots in website directory: $www_dir/$plots_dir_name"
        echo
      fi

    else

      batch_script="$log_dir/batch_atm.$machname.$uniqueID.bash"
      if [ $machname == "nersc" ]; then
        sed 's@SBATCH --time=.*@SBATCH --time='$batch_walltime'@' ./bash_scripts/batch_atm.$machname.bash > $batch_script
        sed -i 's@SBATCH --output=.*@SBATCH --output='$log_dir'/aprime_atm_diags.o'$uniqueID'@' $batch_script
        sed -i 's@SBATCH --error=.*@SBATCH --error='$log_dir'/aprime_atm_diags.e'$uniqueID'@' $batch_script
        echo
        echo "**** Submitting atm batch script: batch_atm.$machname.$uniqueID.bash"
        echo "**** $batch_script"
        echo "**** jobID:"
        sbatch $batch_script
      elif [ $machname == "olcf" ]; then
        sed 's@PBS -l walltime=.*@PBS -l walltime='$batch_walltime'@' ./bash_scripts/batch_atm.$machname.bash > $batch_script
        sed -i 's@PBS -o .*@PBS -o '$log_dir'/aprime_atm_diags.o'$uniqueID'@' $batch_script
        sed -i 's@PBS -e .*@PBS -e '$log_dir'/aprime_atm_diags.e'$uniqueID'@' $batch_script
        echo
        echo "**** Submitting atm batch script: batch_atm.$machname.$uniqueID.bash"
        echo "**** jobID:"
        qsub $batch_script
      else
        echo
        echo "Batch jobs not supported on current machine"
        echo "Please set $run_batch_script to false"
        echo
        exit
      fi
      echo "**** Batch job output/error files aprime_atm_diags.o*/aprime_atm_diags.e* will be available in log directory:"
      echo "**** $log_dir"
      atm_status=-2

    fi

  else

    echo
    echo "Requested test_end_yr_climo is larger than the maximum simulation year. Exiting atm diagnostics..."
    echo "Please set test_end_yr_climo <= ${year_max}"
    echo
    atm_status=3

  fi

else
  atm_status=-1
fi


if [ $generate_ocnice_diags -eq 1 ]; then
  # Check whether requested files for computing climatologies are available
  rpointer_file=${test_archive_dir}/${test_casename}/run/rpointer.ocn
  year_max=`grep -m 1 -Eo '\<[0-9]{4}\>' ${rpointer_file} | awk '{print $1-1}'`

  if [ ${test_end_yr_climo} -le ${year_max} ]; then
 
    if ! $run_batch_script; then

      ./bash_scripts/aprime_ocnice_diags.bash

      ocnice_status=$?

      if [ $ocnice_status -eq 0 ]; then
        # Update www/plots directory with newly generated plots
        cp -u $plots_dir/* $www_dir/$plots_dir_name

        echo
        echo "Updated ocn/ice plots in website directory: $www_dir/$plots_dir_name"
        echo
      fi

    else

      batch_script="$log_dir/batch_ocnice.$machname.$uniqueID.bash"
      if [ $machname == "nersc" ]; then
        sed 's@SBATCH --time=.*@SBATCH --time='$batch_walltime'@' ./bash_scripts/batch_ocnice.$machname.bash > $batch_script
        sed -i 's@SBATCH --output=.*@SBATCH --output='$log_dir'/aprime_ocnice_diags.o'$uniqueID'@' $batch_script
        sed -i 's@SBATCH --error=.*@SBATCH --error='$log_dir'/aprime_ocnice_diags.e'$uniqueID'@' $batch_script
        sed -i 's@SBATCH --nodes=.*@SBATCH --nodes='$mpas_analysis_tasks'@' $batch_script
        echo
        echo "**** Submitting ocn/ice batch script: batch_ocnice.$machname.$uniqueID.bash"
        echo "**** jobID:"
        sbatch $batch_script
      elif [ $machname == "olcf" ]; then
        sed 's@PBS -l walltime=.*@PBS -l walltime='$batch_walltime'@' ./bash_scripts/batch_ocnice.$machname.bash > $batch_script
        sed -i 's@PBS -o .*@PBS -o '$log_dir'/aprime_ocnice_diags.o'$uniqueID'@' $batch_script
        sed -i 's@PBS -e .*@PBS -e '$log_dir'/aprime_ocnice_diags.e'$uniqueID'@' $batch_script
        sed -i 's@PBS -l nodes=.*@PBS -l nodes='$mpas_analysis_tasks'@' $batch_script
        echo
        echo "**** Submitting ocn/ice batch script: batch_ocnice.$machname.$uniqueID.bash"
        echo "**** jobID:"
        qsub $batch_script
      else
        echo
        echo "Batch jobs not supported on current machine"
        echo "Please set $run_batch_script to false"
        echo
        exit
      fi
      echo "**** Batch job output/error files aprime_ocnice_diags.o*/aprime_ocnice_diags.e* will be available in log directory:"
      echo "**** $log_dir"
      ocnice_status=-2

    fi

  else

    echo
    echo "Requested test_end_yr_climo is larger than the maximum simulation year. Exiting ocn/ice diagnostics..."
    echo "Please set test_end_yr_climo <= ${year_max}"
    echo
    ocnice_status=3

  fi

else
  ocnice_status=-1
fi

echo
echo "Status of atmospheric diagnostics: $atm_status"
echo " (0-->success, -1-->diags not invoked, -2-->batch_script, 3-->init error)"
echo "Status of ocean/ice diagnostics: $ocnice_status"
echo " (0-->success, -1-->diags not invoked, -2-->batch_script, 3-->init error)"
echo
echo "All log files, batch scripts, MPAS-Analysis config files available in log directory:"
echo $log_dir
echo "All climo and remapping files for this a-prime run available in scratch directory:"
echo $test_scratch_dir

# GENERATE HTML PAGE IF ASKED
if [ $atm_status -eq 0 ]    || [ $atm_status -eq -2 ]   ||
   [ $ocnice_status -eq 0 ] || [ $ocnice_status -eq -2 ]; then
  source $log_dir/case_info.temp 
  n_cases=${#case_set[@]}
  n_test_cases=$((n_cases - 1))

  for j in `seq 1 $n_test_cases`; do
     if [ $generate_html -eq 1 ]; then
	./bash_scripts/generate_html_index_file.bash	$j \
							$plots_dir \
							$www_dir
     fi
  done
else
  echo
  echo "Neither atmospheric nor ocn/ice diagnostics were successful. HTML page not generated!"
  echo
fi

# COPY THIS RUN SCRIPT TO THE $plots_dir FOR PROVENANCE
cp $0 $log_dir/run_aprime_$uniqueID.bash
