#!/bin/bash

#
# Template driver script to generate coupled diagnostics on edison
#
# Basic usage:
#       1. copy this template to something like run_aprime_$user.bash
#       2. open run_aprime_$user.bash and set user defined, case-specific variables
#       3. execute: ./run_aprime_$user.bash 

# Meaning of acronyms/words used in variable names below:
#	test:		 Test case
#	ref:		 Reference case or 'obs'
#	ts: 		 Time series; e.g. test_begin_yr_ts, here ts refers to time series
#       climateIndex_ts: Time series for climate indexes such as Nino3.4.
#                        NB: if begin_yr_climateIndex_ts=1 and end_yr_climateIndex_ts=9999, the
#                        climate index time series is computed over the full available data set
#	climo: 		 Climatology
#	begin_yr: 	 Model year to start analysis 
#	end_yr:		 Model year to end analysis
#       condense:        Create a new file for each variable with time series data for that variable.
#                        This is used to create climatology (if not pre-computed) and in generating time series plots
#	archive_dir:	 Location of model generated output directory
#	scratch_dir:	 Location of directory where the user wants to store files generated by the diagnostics.
#			 This includes climos, remapped climos, condensed files and data files used for plotting. 
#	short_term_archive:   Adds /atm/hist after the casename. If the data sits in a different structure, add it after
#	                      the casename in test_casename 

# USER DEFINED CASE SPECIFIC VARIABLES TO SPECIFY (REQUIRED)

# Main directory where all analysis output is stored
# (e.g., plots will go in a specific subdirectory of $output_base_dir,
# as will log files, generated climatologies, etc)
export output_base_dir=/dir/to/analysis/output

# MACHINE SPECIFIC VARIABLES (no need to modify these in most cases)
machname4=`echo $HOSTNAME | cut -c1-4`
machname5=`echo $HOSTNAME | cut -c1-5`
machname6=`echo $HOSTNAME | cut -c1-6`
if [ $machname6 == "edison" ]; then # NERSC
  # Project directory
  projdir=/global/project/projectdirs/acme
  # Location of website directory to host the webpage
  export www_dir=/global/project/projectdirs/acme/www/$USER
fi
if [ $machname4 == "rhea" ] || [ $machname5 == "titan" ]; then # OLCF
  projdir=$PROJWORK/cli115
  export www_dir=$HOME/www
fi
if [ $machname5 == "aims4" ] || [ $machname5 == "acme1" ]; then # LLNL (aims4/acme1)
  projdir=/space2
  export www_dir=/var/www/acme/acme-diags/$USER
fi
if [ $machname4 == "wolf" ]; then # LANL
  projdir=/usr/projects/climate/SHARED_CLIMATE
  export www_dir=$output_base_dir/www
fi

# Test case variables
export test_casename=20170313.beta1.A_WCYCL1850S.ne30_oECv3_ICG.edison
export test_archive_dir=/scratch2/scratchdirs/golaz/ACME_simulations
export test_short_term_archive=0
#
# Atmosphere grid resolution name (e.g. ne30, ne60, ne120) 
export test_atm_res=ne30
# MPAS mesh name (e.g. oEC60to30v1, oEC60to30v3, oRRS18to6v1)
#   NB: test_atm_res and test_mpas_mesh_name may change with a different choice of test_casename!
export test_mpas_mesh_name=oEC60to30v3
#
export test_begin_yr_climo=31
export test_end_yr_climo=40
export test_begin_yr_ts=1
export test_end_yr_ts=30
export test_begin_yr_climateIndex_ts=1
export test_end_yr_climateIndex_ts=9999

# Atmosphere switches (True(1)/False(0)) to condense variables, compute climos, remap climos and condensed time series file
# If no pre-processing is done (climatology, remapping), all the switches below should be 1
# If a switch is 0, then the user should ensure that the needed files are in the scratch directory (defined below)
# If a switch is 0 for climo, then the user should ensure that the files in the scratch directory correspond to the intended begin and end years set above.
export test_compute_climo=1
export test_remap_climo=1
export test_condense_field_climo=1	# ignored if test_compute_climo = 0
					# if test_condense_field_climo = 1 and test_compute_climo = 0
					# the script will look for a condensed file 
export test_condense_field_ts=1
export test_remap_ts=1

# Reference case variables (similar to test_case variables)
export ref_case=obs
export ref_archive_dir=$projdir/obs_for_diagnostics
#export ref_case=20160520.A_WCYCL1850.ne30_oEC.edison.alpha6_01
#export ref_archive_dir=/scratch1/scratchdirs/golaz/ACME_simulations
export ref_short_term_archive=0

# ACMEv0 ref_case info for ocn/ice diags
#  IMPORTANT: the ACMEv0 model data MUST have been pre-processed.
#  If this pre-processed data is not available, set ref_case_v0 to None.
export ref_case_v0=B1850C5_ne30_v0.4
export ref_archive_v0_ocndir=$projdir/ACMEv0_lowres/${ref_case_v0}/ocn/postprocessing
export ref_archive_v0_seaicedir=$projdir/ACMEv0_lowres/${ref_case_v0}/ice/postprocessing

# The following are ignored if ref_case=obs
export ref_atm_res=ne30
export ref_mpas_mesh_name=oEC60to30v3
#
export ref_begin_yr_climo=95
export ref_end_yr_climo=100
export ref_begin_yr_ts=95
export ref_end_yr_ts=100
export ref_begin_yr_climateIndex_ts=1
export ref_end_yr_climateIndex_ts=9999
#
export ref_compute_climo=1
export ref_remap_climo=1
export ref_condense_field_climo=1
export ref_condense_field_ts=1
export ref_remap_ts=1

# Select sets of diagnostics to generate (False = 0, True = 1)
export generate_atm_diags=1
export generate_ocnice_diags=1

# The following ocn/ice diagnostic switches are ignored if generate_ocnice_diags is set to 0
export generate_ohc_trends=1
export generate_sst_trends=1
export generate_sst_climo=1
export generate_sss_climo=1
export generate_mld_climo=1
export generate_moc=1
export generate_mht=1
export generate_seaice_trends=1
export generate_seaice_climo=1
export generate_nino34=1

# Generate standalone html file to view plots on a browser, if required
export generate_html=1

# Set options to run a-prime in parallel
#   If run_batch_script=false, aprime_atm_diags.bash and aprime_ocnice_diags.bash are called directly.
#   If run_batch_script=true, aprime_atm_diags.bash and aprime_ocnice_diags.bash are called within
#     a machine-specific batch script. In this case, atmosphere diagnostics are run in background
#     mode onto a single compute node. Ocean/ice diagnostics, on the other hand, grab a number of
#     compute nodes set by 'mpas_analysis_tasks': each ocn/ice task is run on a different node.
#     If all ocn/ice diagnostics are run (by activating all the 'generate' options above), the total
#     number of tasks is equal to 10, hence the default here is 10. The user can decide to reduce
#     mpas_analysis_tasks accordingly, if asking to compute a reduced set of ocn/ice diagnostics.
export run_batch_script=false
export mpas_analysis_tasks=10

###############################################################################################

# OTHER VARIABLES (NOT REQUIRED TO BE CHANGED BY THE USER - DEFAULTS SHOULD WORK, USER PREFERENCE BASED CHANGES)

# Set paths to scratch, logs and plots directories
export test_scratch_dir=$output_base_dir/$test_casename.test.pp
export ref_scratch_dir=$output_base_dir/$ref_case.test.pp

if [ $ref_case == "obs" ]; then
  export plots_dir_name=coupled_diagnostics_${test_casename}_years${test_begin_yr_climo}-${test_end_yr_climo}_vs_${ref_case}
else
  export plots_dir_name=coupled_diagnostics_${test_casename}_years${test_begin_yr_climo}-${test_end_yr_climo}_vs_${ref_case}_years${ref_begin_yr_climo}-${ref_end_yr_climo}
fi

# User can set a custom name for the $plot_dir_name here, if the default (above) is not ideal 
#export plots_dir_name=XXYYY

export log_dir_name=$plots_dir_name.logs

export plots_dir=$output_base_dir/$plots_dir_name
export log_dir=$output_base_dir/$log_dir_name

# Set atm specific paths to mapping and data files locations
export remap_files_dir=$projdir/mapping/maps
export GPCP_regrid_wgt_file=$projdir/mapping/maps/$test_atm_res-to-GPCP.conservative.wgts.nc
export CERES_EBAF_regrid_wgt_file=$projdir/mapping/maps/$test_atm_res-to-CERES-EBAF.conservative.wgts.nc
export ERS_regrid_wgt_file=$projdir/mapping/maps/$test_atm_res-to-ERS.conservative.wgts.nc

# Set ocn/ice specific paths to mapping and region masking file locations
#     remap from MPAS mesh to regular 0.5degx0.5deg grid
#     NB: if this file does not exist, it will be generated by the analysis
export mpas_remapfile=$projdir/mpas_analysis/mapping/map_${test_mpas_mesh_name}_to_0.5x0.5degree_bilinear.nc
#     MPAS-O region mask files containing masking information for the Atlantic basin
#     NB: this file, instead, *needs* to be present 
export mpaso_regions_file=$projdir/mpas_analysis/region_masks/${test_mpas_mesh_name}_Atlantic_region_and_southern_transect.nc

# Set ocn/ice specific paths to data file names and locations
export obs_ocndir=$projdir/observations/Ocean
export obs_seaicedir=$projdir/observations/SeaIce
export obs_sstdir=$obs_ocndir/SST
export obs_sssdir=$obs_ocndir/SSS
export obs_mlddir=$obs_ocndir/MLD
export obs_ninodir=$obs_ocndir/Nino
export obs_mhtdir=$obs_ocndir/MHT
export obs_iceareaNH=$obs_seaicedir/IceArea_timeseries/iceAreaNH_climo.nc
export obs_iceareaSH=$obs_seaicedir/IceArea_timeseries/iceAreaSH_climo.nc
export obs_icevolNH=$obs_seaicedir/PIOMAS/PIOMASvolume_monthly_climo.nc
export obs_icevolSH=none

##############################################################################

######### USER SHOULD NOT NEED TO CHANGE ANYTHING HERE ONWARDS ###############

export coupled_diags_home=$PWD

# LOAD THE MACHINE-SPECIFIC ANACONDA-2.7 ENVIRONMENT
if [ $machname6 == "edison" ]; then # NERSC
  source /opt/modules/default/init/bash  
  module unload python
  module unload python_base
  module use $projdir/software/modulefiles/all
  module load python/anaconda-2.7-acme
fi
if [ $machname4 == "rhea" ] || [ $machname5 == "titan" ]; then # OLCF
  module unload python
  module use $projdir/pwolfram/modulefiles/all
  module load python/anaconda-2.7-climate
fi
if [ $machname5 == "aims4" ] || [ $machname5 == "acme1" ]; then # LLNL (aims4/acme1)
  echo
  echo "Need to set/run the following:"
  echo "  export PATH=/usr/local/anaconda2/bin:$PATH"
  echo "  source activate ACME-UNIFIED   # (on aims4)"
  echo "  source activate ACME_UNIFIED   # (on acme1)"
  echo
fi
if [ $machname4 == "wolf" ]; then # LANL
  module unload python
  module use $projdir/modulefiles/all
  module load python/anaconda-2.7-climate
fi

# PUT THE PROVIDED CASE INFORMATION IN CSH ARRAYS TO FACILITATE READING BY OTHER SCRIPTS
./bash_scripts/setup.bash

# RUN DIAGNOSTICS
if [ $generate_atm_diags -eq 1 ]; then
  # Check whether requested files for computing climatologies are available
  rpointer_file=${test_archive_dir}/${test_casename}/run/rpointer.atm
  year_max=`grep -m 1 -Eo '\<[0-9]{4}\>' ${rpointer_file} | awk '{print $1-1}'`
  if [ $test_end_yr_climo -le $year_max ]; then
    #
    if ! $run_batch_script; then
      ./bash_scripts/aprime_atm_diags.bash
    else
      if [ $machname6 == "edison" ]; then # NERSC
        sbatch ./bash_scripts/batch_atm.NERSC.bash
      else
        echo
        echo "Batch jobs not supported on current machine"
        echo "Please set $run_batch_script to false"
        echo
      fi
    fi
    #
    atm_status=$? 
  else
    echo
    echo "Requested test_end_yr_climo is larger than the maximum simulation year. Exiting atm diagnostics..."
    echo "Please set test_end_yr_climo <= ${year_max}"
    echo
    atm_status=0
  fi
else
  atm_status=0
fi

if [ $generate_ocnice_diags -eq 1 ]; then
  # Check whether requested files for computing climatologies are available
  rpointer_file=${test_archive_dir}/${test_casename}/run/rpointer.ocn
  year_max=`grep -m 1 -Eo '\<[0-9]{4}\>' ${rpointer_file} | awk '{print $1-1}'`
  if [ ${test_end_yr_climo} -le ${year_max} ]; then
    #
    if ! $run_batch_script; then
      ./bash_scripts/aprime_ocnice_diags.bash
    else
      if [ $machname6 == "edison" ]; then # NERSC
        sed -i "s/nodes=.*/nodes=$mpas_analysis_tasks/" ./bash_scripts/batch_ocnice.NERSC.bash
        sbatch ./bash_scripts/batch_ocnice.NERSC.bash
      else
        echo
        echo "Batch jobs not supported on current machine"
        echo "Please set $run_batch_script to false"
        echo
      fi
    fi
    #
    ocnice_status=$?
  else
    echo
    echo "Requested test_end_yr_climo is larger than the maximum simulation year. Exiting ocn/ice diagnostics..."
    echo "Please set test_end_yr_climo <= ${year_max}"
    echo
    ocnice_status=0
  fi
else
  ocnice_status=0
fi

# COPY THIS RUN SCRIPT TO THE $plots_dir FOR PROVENANCE
cp $0 $plots_dir/$0

# GENERATE HTML PAGE IF ASKED
echo
echo "Status of atmospheric diagnostics, 0 implies success or not invoked: $atm_status"
echo "Status of ocean/ice diagnostics, 0 implies success or not invoked: $ocnice_status"
echo

if [ $atm_status -eq 0 ] || [ $ocnice_status -eq 0 ]; then
  source $log_dir/case_info.temp 
  n_cases=${#case_set[@]}
  n_test_cases=$((n_cases - 1))

  for j in `seq 1 $n_test_cases`; do
     if [ $generate_html -eq 1 ]; then
	./bash_scripts/generate_html_index_file.bash	$j \
							$plots_dir \
							$www_dir
     fi
  done
else
  echo
  echo "Neither atmospheric nor ocn/ice diagnostics were successful. HTML page not generated!"
  echo
fi
