; Copyright (c) 2017, UT-BATTELLE, LLC
; All rights reserved.
; 
; This software is released under the BSD license detailed
; in the LICENSE file in the top level a-prime directory
;

load "$NCARG_ROOT/lib/ncarg/nclscripts/csm/gsn_code.ncl"
load "$NCARG_ROOT/lib/ncarg/nclscripts/csm/gsn_csm.ncl"
load "$NCARG_ROOT/lib/ncarg/nclscripts/csm/contributed.ncl"
load "$NCARG_ROOT/lib/ncarg/nclscripts/esmf/ESMF_regridding.ncl"
