#!/usr/bin/env python

'''
Makes a copy of the run_aprime.bash template and optionally renames it as
requested.

Usage:
    get_aprime_template <run_aprime_username.bash>

Authors
-------
Xylar Asay-Davis
'''

import sys
import shutil

inFilePath = '{}/lib/a-prime/run_aprime.bash'.format(sys.prefix)

if len(sys.argv) > 1:
    outFilePath = sys.argv[1]
else:
    outFilePath = 'run_aprime.bash'

shutil.copy2(inFilePath, outFilePath)

